In [1]:
!pip install gensim

Requirement already satisfied: gensim in d:\anaconda\lib\site-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in d:\anaconda\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in d:\anaconda\lib\site-packages (from gensim) (1.15.3)
Requirement already satisfied: smart_open>=1.8.1 in d:\anaconda\lib\site-packages (from gensim) (8.0.1)
Requirement already satisfied: wrapt in d:\anaconda\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)

In [2]:
import os 
os.getcwd()
os.listdir()

['.ipynb_checkpoints',
 'SMSSpamCollection.txt',
 'Spam Ham word2vc avg.ipynb',
 'Untitled.ipynb']

In [3]:
import gensim
from gensim.models import Word2Vec , KeyedVectors

In [4]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

In [5]:
vec_king = wv['king']

In [6]:
vec_king.shape

(300,)

In [7]:
import pandas as pd
message = pd.read_csv('SMSSpamCollection.txt' , sep='\t', names = ["label","message"])

In [8]:
message

     label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [9]:
import re
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ankit\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [10]:
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [11]:
from nltk.corpus import stopwords

stopword_set = set(stopwords.words('english'))
corpus = []

for i in range(0, len(message)):
    # remove extra chars
    rem = re.sub('[^a-zA-Z]', ' ', message['message'][i])
    # make the sentence lower
    rem_lower = rem.lower()
    # split the sentence into words
    words = rem_lower.split()

    # apply stopwords and stemming together
    final = [lemmatizer.lemmatize(word) for word in words if word not in stopword_set]
    
    # join back into a single cleaned string and add to corpus
    corpus.append(' '.join(final))

In [12]:
corpus

['go jurong point crazy available bugis n great world la e buffet cine got amore wat',
 'ok lar joking wif u oni',
 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply',
 'u dun say early hor u c already say',
 'nah think go usf life around though',
 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv',
 'even brother like speak treat like aid patent',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'winner valued network customer selected receivea prize reward claim call claim code kl valid hour',
 'mobile month u r entitled update latest colour mobile camera free call mobile update co free',
 'gonna home soon want talk stuff anymore tonight k cried enough today',
 'six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'searching right word thank breather promise wont take help granted fulfil promise wonderful blessing time',
 'date sunday',
 'xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl',
 'oh k watching',
 'eh u remember spell name yes v naughty make v wet',
 'fine way u feel way gota b',
 'england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq',
 'seriously spell name',
 'going try month ha ha joking',
 'pay first lar da stock comin',
 'aft finish lunch go str lor ard smth lor u finish ur lunch already',
 'ffffffffff alright way meet sooner',
 'forced eat slice really hungry tho suck mark getting worried know sick turn pizza lol',
 'lol always convincing',
 'catch bus frying egg make tea eating mom left dinner feel love',
 'back amp packing car let know room',
 'ahhh work vaguely remember feel like lol',
 'wait still clear sure sarcastic x want live u',
 'yeah got v apologetic n fallen actin like spoilt child got caught till go badly cheer',
 'k tell anything',
 'fear fainting housework quick cuppa',
 'thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged',
 'yup ok go home look timing msg xuhui going learn nd may lesson',
 'oops let know roommate done',
 'see letter b car',
 'anything lor u decide',
 'hello saturday go texting see decided anything tomo trying invite anything',
 'pls go ahead watt wanted sure great weekend abiola',
 'forget tell want need crave love sweet arabian steed mmmmmm yummy',
 'rodger burn msg tried call reply sm free nokia mobile free camcorder please call delivery tomorrow',
 'seeing',
 'great hope like man well endowed lt gt inch',
 'call message missed call',
 'get hep b immunisation nigeria',
 'fair enough anything going',
 'yeah hopefully tyler could maybe ask around bit',
 'u know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker',
 'thinked first time saw class',
 'gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt',
 'k fyi x ride early tomorrow morning crashing place tonight',
 'wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing',
 'sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv',
 'know mallika sherawat yesterday find lt url gt',
 'congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss',
 'sorry call later meeting',
 'tell reached',
 'yes gauti sehwag odi series',
 'gonna pick burger way home even move pain killing',
 'ha ha ha good joke girl situation seeker',
 'part checking iq',
 'sorry roommate took forever ok come',
 'ok lar double check wif da hair dresser already said wun cut v short said cut look nice',
 'valued customer pleased advise following recent review mob awarded bonus prize call',
 'today song dedicated day song u dedicate send ur valuable frnds first rply',
 'urgent ur awarded complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj',
 'hear new divorce barbie come ken stuff',
 'plane give month end',
 'wah lucky man save money hee',
 'finished class',
 'hi babe im home wanna something xx',
 'k k performed',
 'u call',
 'waiting machan call free',
 'thats cool gentleman treat dignity respect',
 'like people much shy pa',
 'operate lt gt',
 'still looking job much ta earn',
 'sorry call later',
 'k call ah',
 'ok way home hi hi',
 'place man',
 'yup next stop',
 'call later network urgnt sm',
 'real u getting yo need ticket one jacket done already used multis',
 'yes started send request make pain came back back bed double coin factory gotta cash nitros',
 'really still tonight babe',
 'ela kano il download come wen ur free',
 'yeah stand close tho catch something',
 'sorry pain ok meet another night spent late afternoon casualty mean done stuff moro includes time sheet sorry',
 'smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling',
 'please call customer service representative pm guaranteed cash prize',
 'havent planning buy later check already lido got show e afternoon u finish work already',
 'free ringtone waiting collected simply text password mix verify get usher britney fml po box mk h ppw',
 'watching telugu movie wat abt u',
 'see finish load loan pay',
 'hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand cause prob u',
 'see cup coffee animation',
 'please text anymore nothing else say',
 'okay name ur price long legal wen pick u ave x am xx',
 'still looking car buy gone driving test yet',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston',
 'umma life vava umma love lot dear',
 'thanks lot wish birthday thanks making birthday truly memorable',
 'aight hit get cash',
 'would ip address test considering computer minecraft server',
 'know grumpy old people mom like better lying always one play joke',
 'dont worry guess busy',
 'plural noun research',
 'going dinner msg',
 'ok wif co like try new thing scared u dun like mah co u said loud',
 'gent trying contact last weekend draw show prize guaranteed call claim code k valid hr ppm',
 'wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'winner u specially selected receive holiday flight inc speak live operator claim p min',
 'goodo yes must speak friday egg potato ratio tortilla needed',
 'hmm uncle informed paying school directly pls buy food',
 'private account statement show unredeemed bonus point claim call identifier code expires',
 'urgent mobile awarded bonus caller prize final try contact u call landline box wr c ppm',
 'new address apple pair malarky',
 'today voda number ending selected receive award match please call quoting claim code standard rate app',
 'going sao mu today done',
 'predict wat time finish buying',
 'good stuff',
 'know yetunde sent money yet sent text bother sending dont involve anything imposed anything first place apologise',
 'room',
 'hey girl r u hope u r well del r bak long time c give call sum time lucyxx',
 'k k much cost',
 'home',
 'dear call tmorrow pls accomodate',
 'first answer question',
 'sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone',
 'want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p',
 'haf msn yijue hotmail com',
 'call meet',
 'check room befor activity',
 'rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try',
 'got c lazy type forgot lect saw pouch like v nice',
 'k text way',
 'sir waiting mail',
 'swt thought nver get tired little thing lovable person coz somtimes little thing occupy biggest part heart gud ni',
 'know pls open back',
 'yes see ya dot',
 'whats staff name taking class u',
 'freemsg replied text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end',
 'ummma call check life begin qatar pls pray hard',
 'k deleted contact',
 'sindu got job birla soft',
 'wine flowing nevering',
 'yup thk cine better co need go plaza mah',
 'ok ur typical reply',
 'per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune',
 'everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done become one',
 'aaooooright work',
 'leaving house',
 'hello love get interview today happy good boy think missing',
 'customer service annoncement new year delivery waiting please call arrange delivery',
 'winner u specially selected receive cash holiday flight inc speak live operator claim',
 'keep safe need miss already envy everyone see real life',
 'new car house parent new job hand',
 'love excited day spend make happy',
 'pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd',
 'bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu',
 'place ur point e culture module already',
 'urgent trying contact last weekend draw show prize guaranteed call claim code valid hr',
 'hi frnd best way avoid missunderstding wit beloved one',
 'great escape fancy bridge need lager see tomo',
 'yes completely form clark also utter waste',
 'sir need axis bank account bank address',
 'hmmm thk sure got time hop ard ya go free abt muz call u discus liao',
 'time coming later',
 'bloody hell cant believe forgot surname mr ill give u clue spanish begin',
 'well gonna finish bath good fine night',
 'let know got money carlos make call',
 'u still going mall',
 'turn friend staying whole show back til lt gt feel free go ahead smoke lt gt worth',
 'text doesnt reply let know log',
 'hi spoke maneesha v like know satisfied experience reply toll free yes',
 'lifted hope offer money need especially end month approach hurt studying anyways gr weekend',
 'lol u trust',
 'ok gentleman treat dignity respect',
 'guy close',
 'going nothing great bye',
 'hello handsome finding job lazy working towards getting back net mummy boytoy miss',
 'haha awesome minute',
 'please call customer service representative freephone pm guaranteed cash prize',
 'got xmas radio time get',
 'jus reached home go bathe first si using net tell u finish k',
 'unique enough find th august www areyouunique co uk',
 'sorry joined league people dont keep touch mean great deal friend time even great personal cost great week',
 'hi finally completed course',
 'stop however suggest stay someone able give or every stool',
 'hope settled new school year wishin gr day',
 'gud mrng dear hav nice day',
 'u got person story',
 'hamster dead hey tmr meet pm orchard mrt',
 'hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx',
 'found enc lt gt',
 'sent lt gt buck',
 'hello darlin ive finished college txt u finish u love kate xxx',
 'account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt',
 'goodmorning sleeping ga',
 'u call alter ok',
 'say like dat dun buy ericsson oso cannot oredi lar',
 'entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went',
 'aight yo dat straight dogg',
 'please give u connection today lt decimal gt refund bill',
 'shoot big load get ready',
 'bruv hope great break rewarding semester',
 'home always chat',
 'k k good study well',
 'yup noe leh',
 'sound great home',
 'finally match heading towards draw prediction',
 'tired slept well past night',
 'easy ah sen got selected mean good',
 'take exam march',
 'yeah think use gt atm register sure anyway help let know sure ready',
 'ok prob take ur time',
 'o called ubandu run without installing hard disk use o copy important file system give repair shop',
 'sorry call later',
 'u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh',
 'new mobile must go txt nokia collect today www tc biz optout gbp mtmsg',
 'would really appreciate call need someone talk',
 'u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries',
 'hey company elama po mudyadhu',
 'life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning',
 'dear good morning',
 'get gandhipuram walk cross cut road right side lt gt street road turn first right',
 'dear going rubber place',
 'sorry battery died yeah',
 'yes tv always available work place',
 'text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny',
 'printed oh lt gt come upstairs',
 'ill little closer like bus stop street',
 'wil reach',
 'new theory argument win situation loses person dont argue ur friend kick amp say always correct',
 'u secret admirer looking make contact u find r reveal think ur special call',
 'tomarrow final hearing laptop case cant',
 'pleassssssseeeeee tel v avent done sportsx',
 'okay shining meant signing sound better',
 'although told u dat baig face watch really like e watch u gave co fr u thanx everything dat u done today touched',
 'u remember old commercial',
 'late said website dont slipper',
 'asked call ok',
 'kallis wont bat nd inning',
 'didnt work oh ok goodnight fix ready time wake dearly missed good night sleep',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ranjith cal drpd deeraj deepak min hold',
 'wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da',
 '',
 'ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff',
 'back lemme know ready',
 'necessarily expect done get back though headin',
 'mmm yummy babe nice jolt suzy',
 'lover need',
 'tried contact reply offer video handset anytime network min unlimited text camcorder reply call',
 'parked next mini coming today think',
 'yup',
 'anyway going shopping co si done yet dun disturb u liao',
 'luton ring ur around h',
 'hey really horny want chat see naked text hot text charged pm unsubscribe text stop',
 'dint come u',
 'wana plan trip sometme',
 'sure yet still trying get hold',
 'ur ringtone service changed free credit go club mobile com choose content stop txt club stop p wk club po box mk wt',
 'evo download flash jealous',
 'ringtone club get uk single chart mobile week choose top quality ringtone message free charge',
 'come mu sorting narcotic situation',
 'night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay',
 'hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com',
 'usf guess might well take car',
 'objection bf coming',
 'thanx',
 'tell rob mack gf theater',
 'awesome see bit',
 'sent type food like',
 'done handed celebration full swing yet',
 'got called tool',
 'wen u miss someone person definitely special u person special miss keep touch gdeve',
 'ok asked money far',
 'okie',
 'yeah think usual guy still passed last night get ahold anybody let know throw',
 'k might come tonight class let early',
 'ok',
 'hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx',
 'life mean lot love life love people life world call friend call world ge',
 'dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense',
 'hey told name gautham ah',
 'haf u found feel stupid da v cam working',
 'oops got bit',
 'much buzy',
 'accidentally deleted message resend please',
 'mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply',
 'unless situation go gurl would appropriate',
 'hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl',
 'cant pick phone right pls send message',
 'need coffee run tomo believe time week already',
 'awesome remember last time got somebody high first time diesel v',
 'shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi',
 'oh way food fridge want go meal tonight',
 'womdarfull actor',
 'sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide',
 'yup remb think book',
 'jos ask u wana meet',
 'lol yes friendship hanging thread cause u buy stuff',
 'themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap',
 'garage key bookshelf',
 'today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy',
 'think ur smart win week weekly quiz text play c winnersclub po box uz gbp week',
 'say give call friend got money definitely buying end week',
 'hi way u day normal way real ur unique hope know u rest mylife hope u find wot lost',
 'made day great day',
 'k k advance happy pongal',
 'hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao',
 'really dude friend afraid',
 'december mobile mths entitled update latest colour camera mobile free call mobile update co free',
 'coffee cake guess',
 'merry christmas babe love ya kiss',
 'hey dont go watch x men lunch haha',
 'cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x',
 'would great guild could meet bristol road somewhere get touch weekend plan take flight good week',
 'problem',
 'call message missed call',
 'hi da today class',
 'say good sign well know track record reading woman',
 'cool text parked',
 'reading text sent meant joke read light',
 'k k apo k good movie',
 'maybe could get book tomo return immediately something',
 'call germany penny per minute call fixed line via access number prepayment direct access',
 'chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor',
 'valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare',
 'ta daaaaa home babe still',
 'cool come havent wined dined',
 'sleeping surfing',
 'sorry call later',
 'u calling right call hand phone',
 'ok great thanx lot',
 'take post come must text happy reading one wiv hello caroline end favourite bless',
 'u hiding stranger',
 'interested like',
 'sister cleared two round birla soft yesterday',
 'gudnite tc practice going',
 'dis yijue jus saw ur mail case huiming havent sent u num dis num',
 'one small prestige problem',
 'fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x',
 'checking really miss seeing jeremiah great month',
 'nah help never iphone',
 'car hour half going apeshit',
 'today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz ur fault basically good',
 'yo guy ever figure much need alcohol jay trying figure much safely spend weed',
 'lt gt ish minute minute ago wtf',
 'thank calling forgot say happy onam sirji fine remembered met insurance person meet qatar insha allah rakhesh ex tata aig joined tissco tayseer',
 'congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age',
 'ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl',

In [13]:
for i, sent in enumerate(corpus):
    print(i,sent)

0 go jurong point crazy available bugis n great world la e buffet cine got amore wat
1 ok lar joking wif u oni
2 free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply
3 u dun say early hor u c already say
4 nah think go usf life around though
5 freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv
6 even brother like speak treat like aid patent
7 per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune
8 winner valued network customer selected receivea prize reward claim call claim code kl valid hour
9 mobile month u r entitled update latest colour mobile camera free call mobile update co free
10 gonna home soon want talk stuff anymore tonight k cried enough today
11 six chance win cash pound txt csh send cost p day day tsandcs apply reply hl info
12 urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw
13 searching right word thank breather promise wont take help granted fulfil promise wonderful blessing time
14 date sunday
15 xxxmobilemovieclub use credit click wap link next txt message click http wap xxxmobilemovieclub com n qjkgighjjgcbl
16 oh k watching
17 eh u remember spell name yes v naughty make v wet
18 fine way u feel way gota b
19 england v macedonia dont miss goal team news txt ur national team eg england try wale scotland txt poboxox w wq
20 seriously spell name
21 going try month ha ha joking
22 pay first lar da stock comin
23 aft finish lunch go str lor ard smth lor u finish ur lunch already
24 ffffffffff alright way meet sooner
25 forced eat slice really hungry tho suck mark getting worried know sick turn pizza lol
26 lol always convincing
27 catch bus frying egg make tea eating mom left dinner feel love
28 back amp packing car let know room
29 ahhh work vaguely remember feel like lol
30 wait still clear sure sarcastic x want live u
31 yeah got v apologetic n fallen actin like spoilt child got caught till go badly cheer
32 k tell anything
33 fear fainting housework quick cuppa
34 thanks subscription ringtone uk mobile charged month please confirm replying yes reply charged
35 yup ok go home look timing msg xuhui going learn nd may lesson
36 oops let know roommate done
37 see letter b car
38 anything lor u decide
39 hello saturday go texting see decided anything tomo trying invite anything
40 pls go ahead watt wanted sure great weekend abiola
41 forget tell want need crave love sweet arabian steed mmmmmm yummy
42 rodger burn msg tried call reply sm free nokia mobile free camcorder please call delivery tomorrow
43 seeing
44 great hope like man well endowed lt gt inch
45 call message missed call
46 get hep b immunisation nigeria
47 fair enough anything going
48 yeah hopefully tyler could maybe ask around bit
49 u know stubborn even want go hospital kept telling mark weak sucker hospital weak sucker
50 thinked first time saw class
51 gram usually run like lt gt half eighth smarter though get almost whole second gram lt gt
52 k fyi x ride early tomorrow morning crashing place tonight
53 wow never realized embarassed accomodations thought liked since best could always seemed happy cave sorry give sorry offered sorry room embarassing
54 sm ac sptv new jersey devil detroit red wing play ice hockey correct incorrect end reply end sptv
55 know mallika sherawat yesterday find lt url gt
56 congrats year special cinema pas call c suprman v matrix starwars etc free bx ip pm dont miss
57 sorry call later meeting
58 tell reached
59 yes gauti sehwag odi series
60 gonna pick burger way home even move pain killing
61 ha ha ha good joke girl situation seeker
62 part checking iq
63 sorry roommate took forever ok come
64 ok lar double check wif da hair dresser already said wun cut v short said cut look nice
65 valued customer pleased advise following recent review mob awarded bonus prize call
66 today song dedicated day song u dedicate send ur valuable frnds first rply
67 urgent ur awarded complimentary trip eurodisinc trav aco entry claim txt dis morefrmmob shracomorsglsuplt l aj
68 hear new divorce barbie come ken stuff
69 plane give month end
70 wah lucky man save money hee
71 finished class
72 hi babe im home wanna something xx
73 k k performed
74 u call
75 waiting machan call free
76 thats cool gentleman treat dignity respect
77 like people much shy pa
78 operate lt gt
79 still looking job much ta earn
80 sorry call later
81 k call ah
82 ok way home hi hi
83 place man
84 yup next stop
85 call later network urgnt sm
86 real u getting yo need ticket one jacket done already used multis
87 yes started send request make pain came back back bed double coin factory gotta cash nitros
88 really still tonight babe
89 ela kano il download come wen ur free
90 yeah stand close tho catch something
91 sorry pain ok meet another night spent late afternoon casualty mean done stuff moro includes time sheet sorry
92 smile pleasure smile pain smile trouble pours like rain smile sum hurt u smile becoz someone still love see u smiling
93 please call customer service representative pm guaranteed cash prize
94 havent planning buy later check already lido got show e afternoon u finish work already
95 free ringtone waiting collected simply text password mix verify get usher britney fml po box mk h ppw
96 watching telugu movie wat abt u
97 see finish load loan pay
98 hi wk ok hols yes bit run forgot hairdresser appointment four need get home n shower beforehand cause prob u
99 see cup coffee animation
100 please text anymore nothing else say
101 okay name ur price long legal wen pick u ave x am xx
102 still looking car buy gone driving test yet
103 per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune
104 wow right mean guess gave boston men changed search location nyc something changed cuz signin page still say boston
105 umma life vava umma love lot dear
106 thanks lot wish birthday thanks making birthday truly memorable
107 aight hit get cash
108 would ip address test considering computer minecraft server
109 know grumpy old people mom like better lying always one play joke
110 dont worry guess busy
111 plural noun research
112 going dinner msg
113 ok wif co like try new thing scared u dun like mah co u said loud
114 gent trying contact last weekend draw show prize guaranteed call claim code k valid hr ppm
115 wa ur openin sentence formal anyway fine juz tt eatin much n puttin weight haha anythin special happened
116 entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went
117 winner u specially selected receive holiday flight inc speak live operator claim p min
118 goodo yes must speak friday egg potato ratio tortilla needed
119 hmm uncle informed paying school directly pls buy food
120 private account statement show unredeemed bonus point claim call identifier code expires
121 urgent mobile awarded bonus caller prize final try contact u call landline box wr c ppm
122 new address apple pair malarky
123 today voda number ending selected receive award match please call quoting claim code standard rate app
124 going sao mu today done
125 predict wat time finish buying
126 good stuff
127 know yetunde sent money yet sent text bother sending dont involve anything imposed anything first place apologise
128 room
129 hey girl r u hope u r well del r bak long time c give call sum time lucyxx
130 k k much cost
131 home
132 dear call tmorrow pls accomodate
133 first answer question
134 sunshine quiz wkly q win top sony dvd player u know country algarve txt ansr sp tyrone
135 want get laid tonight want real dogging location sent direct ur mob join uk largest dogging network bt txting gravel nt ec p msg p
136 haf msn yijue hotmail com
137 call meet
138 check room befor activity
139 rcv msg chat svc free hardcore service text go u get nothing u must age verify yr network try
140 got c lazy type forgot lect saw pouch like v nice
141 k text way
142 sir waiting mail
143 swt thought nver get tired little thing lovable person coz somtimes little thing occupy biggest part heart gud ni
144 know pls open back
145 yes see ya dot
146 whats staff name taking class u
147 freemsg replied text randy sexy female live local luv hear u netcollex ltd p per msg reply stop end
148 ummma call check life begin qatar pls pray hard
149 k deleted contact
150 sindu got job birla soft
151 wine flowing nevering
152 yup thk cine better co need go plaza mah
153 ok ur typical reply
154 per request melle melle oru minnaminunginte nurungu vettam set callertune caller press copy friend callertune
155 everywhere dirt floor window even shirt sometimes open mouth come flowing dream world without half chore time joy lot tv show see guess like thing must exist like rain hail mist time done become one
156 aaooooright work
157 leaving house
158 hello love get interview today happy good boy think missing
159 customer service annoncement new year delivery waiting please call arrange delivery
160 winner u specially selected receive cash holiday flight inc speak live operator claim
161 keep safe need miss already envy everyone see real life
162 new car house parent new job hand
163 love excited day spend make happy
164 pls stop bootydelious f inviting friend reply yes see www sm ac u bootydelious stop send stop frnd
165 bangbabes ur order way u receive service msg download ur content u goto wap bangb tv ur mobile internet service menu
166 place ur point e culture module already
167 urgent trying contact last weekend draw show prize guaranteed call claim code valid hr
168 hi frnd best way avoid missunderstding wit beloved one
169 great escape fancy bridge need lager see tomo
170 yes completely form clark also utter waste
171 sir need axis bank account bank address
172 hmmm thk sure got time hop ard ya go free abt muz call u discus liao
173 time coming later
174 bloody hell cant believe forgot surname mr ill give u clue spanish begin
175 well gonna finish bath good fine night
176 let know got money carlos make call
177 u still going mall
178 turn friend staying whole show back til lt gt feel free go ahead smoke lt gt worth
179 text doesnt reply let know log
180 hi spoke maneesha v like know satisfied experience reply toll free yes
181 lifted hope offer money need especially end month approach hurt studying anyways gr weekend
182 lol u trust
183 ok gentleman treat dignity respect
184 guy close
185 going nothing great bye
186 hello handsome finding job lazy working towards getting back net mummy boytoy miss
187 haha awesome minute
188 please call customer service representative freephone pm guaranteed cash prize
189 got xmas radio time get
190 jus reached home go bathe first si using net tell u finish k
191 unique enough find th august www areyouunique co uk
192 sorry joined league people dont keep touch mean great deal friend time even great personal cost great week
193 hi finally completed course
194 stop however suggest stay someone able give or every stool
195 hope settled new school year wishin gr day
196 gud mrng dear hav nice day
197 u got person story
198 hamster dead hey tmr meet pm orchard mrt
199 hi kate evening hope see tomorrow bit bloody babyjontet txt back u xxx
200 found enc lt gt
201 sent lt gt buck
202 hello darlin ive finished college txt u finish u love kate xxx
203 account refilled successfully inr lt decimal gt keralacircle prepaid account balance r lt decimal gt transaction id kr lt gt
204 goodmorning sleeping ga
205 u call alter ok
206 say like dat dun buy ericsson oso cannot oredi lar
207 entered cabin pa said happy b day bos felt special askd lunch lunch invited apartment went
208 aight yo dat straight dogg
209 please give u connection today lt decimal gt refund bill
210 shoot big load get ready
211 bruv hope great break rewarding semester
212 home always chat
213 k k good study well
214 yup noe leh
215 sound great home
216 finally match heading towards draw prediction
217 tired slept well past night
218 easy ah sen got selected mean good
219 take exam march
220 yeah think use gt atm register sure anyway help let know sure ready
221 ok prob take ur time
222 o called ubandu run without installing hard disk use o copy important file system give repair shop
223 sorry call later
224 u say leh course nothing happen lar say v romantic jus bit lor thk e nite scenery nice leh
225 new mobile must go txt nokia collect today www tc biz optout gbp mtmsg
226 would really appreciate call need someone talk
227 u meet ur dream partner soon ur career flyng start find free txt horo followed ur star sign e g horo aries
228 hey company elama po mudyadhu
229 life strict teacher bcoz teacher teach lesson amp conduct exam life first conduct exam amp teach lesson happy morning
230 dear good morning
231 get gandhipuram walk cross cut road right side lt gt street road turn first right
232 dear going rubber place
233 sorry battery died yeah
234 yes tv always available work place
235 text meet someone sexy today u find date even flirt u join p reply name age eg sam msg recd thirtyeight penny
236 printed oh lt gt come upstairs
237 ill little closer like bus stop street
238 wil reach
239 new theory argument win situation loses person dont argue ur friend kick amp say always correct
240 u secret admirer looking make contact u find r reveal think ur special call
241 tomarrow final hearing laptop case cant
242 pleassssssseeeeee tel v avent done sportsx
243 okay shining meant signing sound better
244 although told u dat baig face watch really like e watch u gave co fr u thanx everything dat u done today touched
245 u remember old commercial
246 late said website dont slipper
247 asked call ok
248 kallis wont bat nd inning
249 didnt work oh ok goodnight fix ready time wake dearly missed good night sleep
250 congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age
251 ranjith cal drpd deeraj deepak min hold
252 wen ur lovable bcums angry wid u dnt take seriously coz angry childish n true way showing deep affection care n luv kettoda manda nice day da
253
254 ups day also shipping company take wks way usps take week get lag may bribe nipost get stuff
255 back lemme know ready
256 necessarily expect done get back though headin
257 mmm yummy babe nice jolt suzy
258 lover need
259 tried contact reply offer video handset anytime network min unlimited text camcorder reply call
260 parked next mini coming today think
261 yup
262 anyway going shopping co si done yet dun disturb u liao
263 luton ring ur around h
264 hey really horny want chat see naked text hot text charged pm unsubscribe text stop
265 dint come u
266 wana plan trip sometme
267 sure yet still trying get hold
268 ur ringtone service changed free credit go club mobile com choose content stop txt club stop p wk club po box mk wt
269 evo download flash jealous
270 ringtone club get uk single chart mobile week choose top quality ringtone message free charge
271 come mu sorting narcotic situation
272 night ended another day morning come special way may smile like sunny ray leaf worry blue blue bay
273 hmv bonus special pound genuine hmv voucher answer easy question play send hmv info www percent real com
274 usf guess might well take car
275 objection bf coming
276 thanx
277 tell rob mack gf theater
278 awesome see bit
279 sent type food like
280 done handed celebration full swing yet
281 got called tool
282 wen u miss someone person definitely special u person special miss keep touch gdeve
283 ok asked money far
284 okie
285 yeah think usual guy still passed last night get ahold anybody let know throw
286 k might come tonight class let early
287 ok
288 hi baby im cruisin girl friend r u give call hour home thats alright fone fone love jenny xxx
289 life mean lot love life love people life world call friend call world ge
290 dear shall mail tonite busy street shall update tonite thing looking ok varunnathu edukkukayee raksha ollu good one real sense
291 hey told name gautham ah
292 haf u found feel stupid da v cam working
293 oops got bit
294 much buzy
295 accidentally deleted message resend please
296 mobile customer may claim free camera phone upgrade pay go sim card loyalty call offer end thfeb c apply
297 unless situation go gurl would appropriate
298 hurt tease make cry end life die plz keep one rose grave say stupid miss u nice day bslvyl
299 cant pick phone right pls send message
300 need coffee run tomo believe time week already
301 awesome remember last time got somebody high first time diesel v
302 shit really shocking scary cant imagine second def night u think somewhere could crash night save taxi
303 oh way food fridge want go meal tonight
304 womdarfull actor
305 sm ac blind date u rodds aberdeen united kingdom check http img sm ac w icmb cktz r blind date send hide
306 yup remb think book
307 jos ask u wana meet
308 lol yes friendship hanging thread cause u buy stuff
309 themob check newest selection content game tone gossip babe sport keep mobile fit funky text wap
310 garage key bookshelf
311 today accept day u accept brother sister lover dear best clos lvblefrnd jstfrnd cutefrnd lifpartnr belovd swtheart bstfrnd rply mean enemy
312 think ur smart win week weekly quiz text play c winnersclub po box uz gbp week
313 say give call friend got money definitely buying end week
314 hi way u day normal way real ur unique hope know u rest mylife hope u find wot lost
315 made day great day
316 k k advance happy pongal
317 hmmm guess go kb n power yoga haha dunno tahan power yoga anot thk got lo oso forgot liao
318 really dude friend afraid
319 december mobile mths entitled update latest colour camera mobile free call mobile update co free
320 coffee cake guess
321 merry christmas babe love ya kiss
322 hey dont go watch x men lunch haha
323 cud u tell ppl im gona b bit l co bus hav gon past co full im still waitin pete x
324 would great guild could meet bristol road somewhere get touch weekend plan take flight good week
325 problem
326 call message missed call
327 hi da today class
328 say good sign well know track record reading woman
329 cool text parked
330 reading text sent meant joke read light
331 k k apo k good movie
332 maybe could get book tomo return immediately something
333 call germany penny per minute call fixed line via access number prepayment direct access
334 chance might evaporated soon violated privacy stealing phone number employer paperwork cool please contact report supervisor
335 valentine day special win quiz take partner trip lifetime send go p msg rcvd custcare
336 ta daaaaa home babe still
337 cool come havent wined dined
338 sleeping surfing
339 sorry call later
340 u calling right call hand phone
341 ok great thanx lot
342 take post come must text happy reading one wiv hello caroline end favourite bless
343 u hiding stranger
344 interested like
345 sister cleared two round birla soft yesterday
346 gudnite tc practice going
347 dis yijue jus saw ur mail case huiming havent sent u num dis num
348 one small prestige problem
349 fancy shag interested sextextuk com txt xxuk suzy txts cost per msg tncs website x
350 checking really miss seeing jeremiah great month
351 nah help never iphone
352 car hour half going apeshit
353 today sorry day ever angry ever misbehaved hurt plz plz slap urself bcoz ur fault basically good
354 yo guy ever figure much need alcohol jay trying figure much safely spend weed
355 lt gt ish minute minute ago wtf
356 thank calling forgot say happy onam sirji fine remembered met insurance person meet qatar insha allah rakhesh ex tata aig joined tissco tayseer
357 congratulation ur awarded cd voucher gift guaranteed free entry wkly draw txt music tncs www ldew com win ppmx age
358 ur cash balance currently pound maximize ur cash send cash p msg cc hg suite land row w j hl
359 actor work work evening sleep late since unemployed moment always sleep late unemployed every day saturday

In [14]:
from gensim.utils import simple_preprocess
# the simpl_preprocess takes the sentence and make it inot he list of words for onw snetence 
# where each index stores the words of one sentence

In [16]:
words = []

for sent in corpus:
  words.append(simple_preprocess(sent))

In [17]:
words

[['go',
  'jurong',
  'point',
  'crazy',
  'available',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'wkly',
  'comp',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply'],
 ['dun', 'say', 'early', 'hor', 'already', 'say'],
 ['nah', 'think', 'go', 'usf', 'life', 'around', 'though'],
 ['freemsg',
  'hey',
  'darling',
  'week',
  'word',
  'back',
  'like',
  'fun',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'send',
  'rcv'],
 ['even', 'brother', 'like', 'speak', 'treat', 'like', 'aid', 'patent'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['winner',
  'valued',
  'network',
  'customer',
  'selected',
  'receivea',
  'prize',
  'reward',
  'claim',
  'call',
  'claim',
  'code',
  'kl',
  'valid',
  'hour'],
 ['mobile',
  'month',
  'entitled',
  'update',
  'latest',
  'colour',
  'mobile',
  'camera',
  'free',
  'call',
  'mobile',
  'update',
  'co',
  'free'],
 ['gonna',
  'home',
  'soon',
  'want',
  'talk',
  'stuff',
  'anymore',
  'tonight',
  'cried',
  'enough',
  'today'],
 ['six',
  'chance',
  'win',
  'cash',
  'pound',
  'txt',
  'csh',
  'send',
  'cost',
  'day',
  'day',
  'tsandcs',
  'apply',
  'reply',
  'hl',
  'info'],
 ['urgent',
  'week',
  'free',
  'membership',
  'prize',
  'jackpot',
  'txt',
  'word',
  'claim',
  'www',
  'dbuk',
  'net',
  'lccltd',
  'pobox',
  'ldnw',
  'rw'],
 ['searching',
  'right',
  'word',
  'thank',
  'breather',
  'promise',
  'wont',
  'take',
  'help',
  'granted',
  'fulfil',
  'promise',
  'wonderful',
  'blessing',
  'time'],
 ['date', 'sunday'],
 ['use',
  'credit',
  'click',
  'wap',
  'link',
  'next',
  'txt',
  'message',
  'click',
  'http',
  'wap',
  'com',
  'qjkgighjjgcbl'],
 ['oh', 'watching'],
 ['eh', 'remember', 'spell', 'name', 'yes', 'naughty', 'make', 'wet'],
 ['fine', 'way', 'feel', 'way', 'gota'],
 ['england',
  'macedonia',
  'dont',
  'miss',
  'goal',
  'team',
  'news',
  'txt',
  'ur',
  'national',
  'team',
  'eg',
  'england',
  'try',
  'wale',
  'scotland',
  'txt',
  'poboxox',
  'wq'],
 ['seriously', 'spell', 'name'],
 ['going', 'try', 'month', 'ha', 'ha', 'joking'],
 ['pay', 'first', 'lar', 'da', 'stock', 'comin'],
 ['aft',
  'finish',
  'lunch',
  'go',
  'str',
  'lor',
  'ard',
  'smth',
  'lor',
  'finish',
  'ur',
  'lunch',
  'already'],
 ['ffffffffff', 'alright', 'way', 'meet', 'sooner'],
 ['forced',
  'eat',
  'slice',
  'really',
  'hungry',
  'tho',
  'suck',
  'mark',
  'getting',
  'worried',
  'know',
  'sick',
  'turn',
  'pizza',
  'lol'],
 ['lol', 'always', 'convincing'],
 ['catch',
  'bus',
  'frying',
  'egg',
  'make',
  'tea',
  'eating',
  'mom',
  'left',
  'dinner',
  'feel',
  'love'],
 ['back', 'amp', 'packing', 'car', 'let', 'know', 'room'],
 ['ahhh', 'work', 'vaguely', 'remember', 'feel', 'like', 'lol'],
 ['wait', 'still', 'clear', 'sure', 'sarcastic', 'want', 'live'],
 ['yeah',
  'got',
  'apologetic',
  'fallen',
  'actin',
  'like',
  'spoilt',
  'child',
  'got',
  'caught',
  'till',
  'go',
  'badly',
  'cheer'],
 ['tell', 'anything'],
 ['fear', 'fainting', 'housework', 'quick', 'cuppa'],
 ['thanks',
  'subscription',
  'ringtone',
  'uk',
  'mobile',
  'charged',
  'month',
  'please',
  'confirm',
  'replying',
  'yes',
  'reply',
  'charged'],
 ['yup',
  'ok',
  'go',
  'home',
  'look',
  'timing',
  'msg',
  'xuhui',
  'going',
  'learn',
  'nd',
  'may',
  'lesson'],
 ['oops', 'let', 'know', 'roommate', 'done'],
 ['see', 'letter', 'car'],
 ['anything', 'lor', 'decide'],
 ['hello',
  'saturday',
  'go',
  'texting',
  'see',
  'decided',
  'anything',
  'tomo',
  'trying',
  'invite',
  'anything'],
 ['pls',
  'go',
  'ahead',
  'watt',
  'wanted',
  'sure',
  'great',
  'weekend',
  'abiola'],
 ['forget',
  'tell',
  'want',
  'need',
  'crave',
  'love',
  'sweet',
  'arabian',
  'steed',
  'mmmmmm',
  'yummy'],
 ['rodger',
  'burn',
  'msg',
  'tried',
  'call',
  'reply',
  'sm',
  'free',
  'nokia',
  'mobile',
  'free',
  'camcorder',
  'please',
  'call',
  'delivery',
  'tomorrow'],
 ['seeing'],
 ['great', 'hope', 'like', 'man', 'well', 'endowed', 'lt', 'gt', 'inch'],
 ['call', 'message', 'missed', 'call'],
 ['get', 'hep', 'immunisation', 'nigeria'],
 ['fair', 'enough', 'anything', 'going'],
 ['yeah', 'hopefully', 'tyler', 'could', 'maybe', 'ask', 'around', 'bit'],
 ['know',
  'stubborn',
  'even',
  'want',
  'go',
  'hospital',
  'kept',
  'telling',
  'mark',
  'weak',
  'sucker',
  'hospital',
  'weak',
  'sucker'],
 ['thinked', 'first', 'time', 'saw', 'class'],
 ['gram',
  'usually',
  'run',
  'like',
  'lt',
  'gt',
  'half',
  'eighth',
  'smarter',
  'though',
  'get',
  'almost',
  'whole',
  'second',
  'gram',
  'lt',
  'gt'],
 ['fyi',
  'ride',
  'early',
  'tomorrow',
  'morning',
  'crashing',
  'place',
  'tonight'],
 ['wow',
  'never',
  'realized',
  'embarassed',
  'accomodations',
  'thought',
  'liked',
  'since',
  'best',
  'could',
  'always',
  'seemed',
  'happy',
  'cave',
  'sorry',
  'give',
  'sorry',
  'offered',
  'sorry',
  'room',
  'embarassing'],
 ['sm',
  'ac',
  'sptv',
  'new',
  'jersey',
  'devil',
  'detroit',
  'red',
  'wing',
  'play',
  'ice',
  'hockey',
  'correct',
  'incorrect',
  'end',
  'reply',
  'end',
  'sptv'],
 ['know', 'mallika', 'sherawat', 'yesterday', 'find', 'lt', 'url', 'gt'],
 ['congrats',
  'year',
  'special',
  'cinema',
  'pas',
  'call',
  'suprman',
  'matrix',
  'starwars',
  'etc',
  'free',
  'bx',
  'ip',
  'pm',
  'dont',
  'miss'],
 ['sorry', 'call', 'later', 'meeting'],
 ['tell', 'reached'],
 ['yes', 'gauti', 'sehwag', 'odi', 'series'],
 ['gonna', 'pick', 'burger', 'way', 'home', 'even', 'move', 'pain', 'killing'],
 ['ha', 'ha', 'ha', 'good', 'joke', 'girl', 'situation', 'seeker'],
 ['part', 'checking', 'iq'],
 ['sorry', 'roommate', 'took', 'forever', 'ok', 'come'],
 ['ok',
  'lar',
  'double',
  'check',
  'wif',
  'da',
  'hair',
  'dresser',
  'already',
  'said',
  'wun',
  'cut',
  'short',
  'said',
  'cut',
  'look',
  'nice'],
 ['valued',
  'customer',
  'pleased',
  'advise',
  'following',
  'recent',
  'review',
  'mob',
  'awarded',
  'bonus',
  'prize',
  'call'],
 ['today',
  'song',
  'dedicated',
  'day',
  'song',
  'dedicate',
  'send',
  'ur',
  'valuable',
  'frnds',
  'first',
  'rply'],
 ['urgent',
  'ur',
  'awarded',
  'complimentary',
  'trip',
  'eurodisinc',
  'trav',
  'aco',
  'entry',
  'claim',
  'txt',
  'dis',
  'morefrmmob',
  'aj'],
 ['hear', 'new', 'divorce', 'barbie', 'come', 'ken', 'stuff'],
 ['plane', 'give', 'month', 'end'],
 ['wah', 'lucky', 'man', 'save', 'money', 'hee'],
 ['finished', 'class'],
 ['hi', 'babe', 'im', 'home', 'wanna', 'something', 'xx'],
 ['performed'],
 ['call'],
 ['waiting', 'machan', 'call', 'free'],
 ['thats', 'cool', 'gentleman', 'treat', 'dignity', 'respect'],
 ['like', 'people', 'much', 'shy', 'pa'],
 ['operate', 'lt', 'gt'],
 ['still', 'looking', 'job', 'much', 'ta', 'earn'],
 ['sorry', 'call', 'later'],
 ['call', 'ah'],
 ['ok', 'way', 'home', 'hi', 'hi'],
 ['place', 'man'],
 ['yup', 'next', 'stop'],
 ['call', 'later', 'network', 'urgnt', 'sm'],
 ['real',
  'getting',
  'yo',
  'need',
  'ticket',
  'one',
  'jacket',
  'done',
  'already',
  'used',
  'multis'],
 ['yes',
  'started',
  'send',
  'request',
  'make',
  'pain',
  'came',
  'back',
  'back',
  'bed',
  'double',
  'coin',
  'factory',
  'gotta',
  'cash',
  'nitros'],
 ['really', 'still', 'tonight', 'babe'],
 ['ela', 'kano', 'il', 'download', 'come', 'wen', 'ur', 'free'],
 ['yeah', 'stand', 'close', 'tho', 'catch', 'something'],
 ['sorry',
  'pain',
  'ok',
  'meet',
  'another',
  'night',
  'spent',
  'late',
  'afternoon',
  'casualty',
  'mean',
  'done',
  'stuff',
  'moro',
  'includes',
  'time',
  'sheet',
  'sorry'],
 ['smile',
  'pleasure',
  'smile',
  'pain',
  'smile',
  'trouble',
  'pours',
  'like',
  'rain',
  'smile',
  'sum',
  'hurt',
  'smile',
  'becoz',
  'someone',
  'still',
  'love',
  'see',
  'smiling'],
 ['please',
  'call',
  'customer',
  'service',
  'representative',
  'pm',
  'guaranteed',
  'cash',
  'prize'],
 ['havent',
  'planning',
  'buy',
  'later',
  'check',
  'already',
  'lido',
  'got',
  'show',
  'afternoon',
  'finish',
  'work',
  'already'],
 ['free',
  'ringtone',
  'waiting',
  'collected',
  'simply',
  'text',
  'password',
  'mix',
  'verify',
  'get',
  'usher',
  'britney',
  'fml',
  'po',
  'box',
  'mk',
  'ppw'],
 ['watching', 'telugu', 'movie', 'wat', 'abt'],
 ['see', 'finish', 'load', 'loan', 'pay'],
 ['hi',
  'wk',
  'ok',
  'hols',
  'yes',
  'bit',
  'run',
  'forgot',
  'hairdresser',
  'appointment',
  'four',
  'need',
  'get',
  'home',
  'shower',
  'beforehand',
  'cause',
  'prob'],
 ['see', 'cup', 'coffee', 'animation'],
 ['please', 'text', 'anymore', 'nothing', 'else', 'say'],
 ['okay',
  'name',
  'ur',
  'price',
  'long',
  'legal',
  'wen',
  'pick',
  'ave',
  'am',
  'xx'],
 ['still', 'looking', 'car', 'buy', 'gone', 'driving', 'test', 'yet'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['wow',
  'right',
  'mean',
  'guess',
  'gave',
  'boston',
  'men',
  'changed',
  'search',
  'location',
  'nyc',
  'something',
  'changed',
  'cuz',
  'signin',
  'page',
  'still',
  'say',
  'boston'],
 ['umma', 'life', 'vava', 'umma', 'love', 'lot', 'dear'],
 ['thanks',
  'lot',
  'wish',
  'birthday',
  'thanks',
  'making',
  'birthday',
  'truly',
  'memorable'],
 ['aight', 'hit', 'get', 'cash'],
 ['would',
  'ip',
  'address',
  'test',
  'considering',
  'computer',
  'minecraft',
  'server'],
 ['know',
  'grumpy',
  'old',
  'people',
  'mom',
  'like',
  'better',
  'lying',
  'always',
  'one',
  'play',
  'joke'],
 ['dont', 'worry', 'guess', 'busy'],
 ['plural', 'noun', 'research'],
 ['going', 'dinner', 'msg'],
 ['ok',
  'wif',
  'co',
  'like',
  'try',
  'new',
  'thing',
  'scared',
  'dun',
  'like',
  'mah',
  'co',
  'said',
  'loud'],
 ['gent',
  'trying',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr',
  'ppm'],
 ['wa',
  'ur',
  'openin',
  'sentence',
  'formal',
  'anyway',
  'fine',
  'juz',
  'tt',
  'eatin',
  'much',
  'puttin',
  'weight',
  'haha',
  'anythin',
  'special',
  'happened'],
 ['entered',
  'cabin',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invited',
  'apartment',
  'went'],
 ['winner',
  'specially',
  'selected',
  'receive',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'operator',
  'claim',
  'min'],
 ['goodo',
  'yes',
  'must',
  'speak',
  'friday',
  'egg',
  'potato',
  'ratio',
  'tortilla',
  'needed'],
 ['hmm',
  'uncle',
  'informed',
  'paying',
  'school',
  'directly',
  'pls',
  'buy',
  'food'],
 ['private',
  'account',
  'statement',
  'show',
  'unredeemed',
  'bonus',
  'point',
  'claim',
  'call',
  'identifier',
  'code',
  'expires'],
 ['urgent',
  'mobile',
  'awarded',
  'bonus',
  'caller',
  'prize',
  'final',
  'try',
  'contact',
  'call',
  'landline',
  'box',
  'wr',
  'ppm'],
 ['new', 'address', 'apple', 'pair', 'malarky'],
 ['today',
  'voda',
  'number',
  'ending',
  'selected',
  'receive',
  'award',
  'match',
  'please',
  'call',
  'quoting',
  'claim',
  'code',
  'standard',
  'rate',
  'app'],
 ['going', 'sao', 'mu', 'today', 'done'],
 ['predict', 'wat', 'time', 'finish', 'buying'],
 ['good', 'stuff'],
 ['know',
  'yetunde',
  'sent',
  'money',
  'yet',
  'sent',
  'text',
  'bother',
  'sending',
  'dont',
  'involve',
  'anything',
  'imposed',
  'anything',
  'first',
  'place',
  'apologise'],
 ['room'],
 ['hey',
  'girl',
  'hope',
  'well',
  'del',
  'bak',
  'long',
  'time',
  'give',
  'call',
  'sum',
  'time',
  'lucyxx'],
 ['much', 'cost'],
 ['home'],
 ['dear', 'call', 'tmorrow', 'pls', 'accomodate'],
 ['first', 'answer', 'question'],
 ['sunshine',
  'quiz',
  'wkly',
  'win',
  'top',
  'sony',
  'dvd',
  'player',
  'know',
  'country',
  'algarve',
  'txt',
  'ansr',
  'sp',
  'tyrone'],
 ['want',
  'get',
  'laid',
  'tonight',
  'want',
  'real',
  'dogging',
  'location',
  'sent',
  'direct',
  'ur',
  'mob',
  'join',
  'uk',
  'largest',
  'dogging',
  'network',
  'bt',
  'txting',
  'gravel',
  'nt',
  'ec',
  'msg'],
 ['haf', 'msn', 'yijue', 'hotmail', 'com'],
 ['call', 'meet'],
 ['check', 'room', 'befor', 'activity'],
 ['rcv',
  'msg',
  'chat',
  'svc',
  'free',
  'hardcore',
  'service',
  'text',
  'go',
  'get',
  'nothing',
  'must',
  'age',
  'verify',
  'yr',
  'network',
  'try'],
 ['got', 'lazy', 'type', 'forgot', 'lect', 'saw', 'pouch', 'like', 'nice'],
 ['text', 'way'],
 ['sir', 'waiting', 'mail'],
 ['swt',
  'thought',
  'nver',
  'get',
  'tired',
  'little',
  'thing',
  'lovable',
  'person',
  'coz',
  'somtimes',
  'little',
  'thing',
  'occupy',
  'biggest',
  'part',
  'heart',
  'gud',
  'ni'],
 ['know', 'pls', 'open', 'back'],
 ['yes', 'see', 'ya', 'dot'],
 ['whats', 'staff', 'name', 'taking', 'class'],
 ['freemsg',
  'replied',
  'text',
  'randy',
  'sexy',
  'female',
  'live',
  'local',
  'luv',
  'hear',
  'netcollex',
  'ltd',
  'per',
  'msg',
  'reply',
  'stop',
  'end'],
 ['ummma', 'call', 'check', 'life', 'begin', 'qatar', 'pls', 'pray', 'hard'],
 ['deleted', 'contact'],
 ['sindu', 'got', 'job', 'birla', 'soft'],
 ['wine', 'flowing', 'nevering'],
 ['yup', 'thk', 'cine', 'better', 'co', 'need', 'go', 'plaza', 'mah'],
 ['ok', 'ur', 'typical', 'reply'],
 ['per',
  'request',
  'melle',
  'melle',
  'oru',
  'minnaminunginte',
  'nurungu',
  'vettam',
  'set',
  'callertune',
  'caller',
  'press',
  'copy',
  'friend',
  'callertune'],
 ['everywhere',
  'dirt',
  'floor',
  'window',
  'even',
  'shirt',
  'sometimes',
  'open',
  'mouth',
  'come',
  'flowing',
  'dream',
  'world',
  'without',
  'half',
  'chore',
  'time',
  'joy',
  'lot',
  'tv',
  'show',
  'see',
  'guess',
  'like',
  'thing',
  'must',
  'exist',
  'like',
  'rain',
  'hail',
  'mist',
  'time',
  'done',
  'become',
  'one'],
 ['aaooooright', 'work'],
 ['leaving', 'house'],
 ['hello',
  'love',
  'get',
  'interview',
  'today',
  'happy',
  'good',
  'boy',
  'think',
  'missing'],
 ['customer',
  'service',
  'annoncement',
  'new',
  'year',
  'delivery',
  'waiting',
  'please',
  'call',
  'arrange',
  'delivery'],
 ['winner',
  'specially',
  'selected',
  'receive',
  'cash',
  'holiday',
  'flight',
  'inc',
  'speak',
  'live',
  'operator',
  'claim'],
 ['keep',
  'safe',
  'need',
  'miss',
  'already',
  'envy',
  'everyone',
  'see',
  'real',
  'life'],
 ['new', 'car', 'house', 'parent', 'new', 'job', 'hand'],
 ['love', 'excited', 'day', 'spend', 'make', 'happy'],
 ['pls',
  'stop',
  'bootydelious',
  'inviting',
  'friend',
  'reply',
  'yes',
  'see',
  'www',
  'sm',
  'ac',
  'bootydelious',
  'stop',
  'send',
  'stop',
  'frnd'],
 ['bangbabes',
  'ur',
  'order',
  'way',
  'receive',
  'service',
  'msg',
  'download',
  'ur',
  'content',
  'goto',
  'wap',
  'bangb',
  'tv',
  'ur',
  'mobile',
  'internet',
  'service',
  'menu'],
 ['place', 'ur', 'point', 'culture', 'module', 'already'],
 ['urgent',
  'trying',
  'contact',
  'last',
  'weekend',
  'draw',
  'show',
  'prize',
  'guaranteed',
  'call',
  'claim',
  'code',
  'valid',
  'hr'],
 ['hi',
  'frnd',
  'best',
  'way',
  'avoid',
  'missunderstding',
  'wit',
  'beloved',
  'one'],
 ['great', 'escape', 'fancy', 'bridge', 'need', 'lager', 'see', 'tomo'],
 ['yes', 'completely', 'form', 'clark', 'also', 'utter', 'waste'],
 ['sir', 'need', 'axis', 'bank', 'account', 'bank', 'address'],
 ['hmmm',
  'thk',
  'sure',
  'got',
  'time',
  'hop',
  'ard',
  'ya',
  'go',
  'free',
  'abt',
  'muz',
  'call',
  'discus',
  'liao'],
 ['time', 'coming', 'later'],
 ['bloody',
  'hell',
  'cant',
  'believe',
  'forgot',
  'surname',
  'mr',
  'ill',
  'give',
  'clue',
  'spanish',
  'begin'],
 ['well', 'gonna', 'finish', 'bath', 'good', 'fine', 'night'],
 ['let', 'know', 'got', 'money', 'carlos', 'make', 'call'],
 ['still', 'going', 'mall'],
 ['turn',
  'friend',
  'staying',
  'whole',
  'show',
  'back',
  'til',
  'lt',
  'gt',
  'feel',
  'free',
  'go',
  'ahead',
  'smoke',
  'lt',
  'gt',
  'worth'],
 ['text', 'doesnt', 'reply', 'let', 'know', 'log'],
 ['hi',
  'spoke',
  'maneesha',
  'like',
  'know',
  'satisfied',
  'experience',
  'reply',
  'toll',
  'free',
  'yes'],
 ['lifted',
  'hope',
  'offer',
  'money',
  'need',
  'especially',
  'end',
  'month',
  'approach',
  'hurt',
  'studying',
  'anyways',
  'gr',
  'weekend'],
 ['lol', 'trust'],
 ['ok', 'gentleman', 'treat', 'dignity', 'respect'],
 ['guy', 'close'],
 ['going', 'nothing', 'great', 'bye'],
 ['hello',
  'handsome',
  'finding',
  'job',
  'lazy',
  'working',
  'towards',
  'getting',
  'back',
  'net',
  'mummy',
  'boytoy',
  'miss'],
 ['haha', 'awesome', 'minute'],
 ['please',
  'call',
  'customer',
  'service',
  'representative',
  'freephone',
  'pm',
  'guaranteed',
  'cash',
  'prize'],
 ['got', 'xmas', 'radio', 'time', 'get'],
 ['jus',
  'reached',
  'home',
  'go',
  'bathe',
  'first',
  'si',
  'using',
  'net',
  'tell',
  'finish'],
 ['unique',
  'enough',
  'find',
  'th',
  'august',
  'www',
  'areyouunique',
  'co',
  'uk'],
 ['sorry',
  'joined',
  'league',
  'people',
  'dont',
  'keep',
  'touch',
  'mean',
  'great',
  'deal',
  'friend',
  'time',
  'even',
  'great',
  'personal',
  'cost',
  'great',
  'week'],
 ['hi', 'finally', 'completed', 'course'],
 ['stop',
  'however',
  'suggest',
  'stay',
  'someone',
  'able',
  'give',
  'or',
  'every',
  'stool'],
 ['hope', 'settled', 'new', 'school', 'year', 'wishin', 'gr', 'day'],
 ['gud', 'mrng', 'dear', 'hav', 'nice', 'day'],
 ['got', 'person', 'story'],
 ['hamster', 'dead', 'hey', 'tmr', 'meet', 'pm', 'orchard', 'mrt'],
 ['hi',
  'kate',
  'evening',
  'hope',
  'see',
  'tomorrow',
  'bit',
  'bloody',
  'babyjontet',
  'txt',
  'back',
  'xxx'],
 ['found', 'enc', 'lt', 'gt'],
 ['sent', 'lt', 'gt', 'buck'],
 ['hello',
  'darlin',
  'ive',
  'finished',
  'college',
  'txt',
  'finish',
  'love',
  'kate',
  'xxx'],
 ['account',
  'refilled',
  'successfully',
  'inr',
  'lt',
  'decimal',
  'gt',
  'keralacircle',
  'prepaid',
  'account',
  'balance',
  'lt',
  'decimal',
  'gt',
  'transaction',
  'id',
  'kr',
  'lt',
  'gt'],
 ['goodmorning', 'sleeping', 'ga'],
 ['call', 'alter', 'ok'],
 ['say',
  'like',
  'dat',
  'dun',
  'buy',
  'ericsson',
  'oso',
  'cannot',
  'oredi',
  'lar'],
 ['entered',
  'cabin',
  'pa',
  'said',
  'happy',
  'day',
  'bos',
  'felt',
  'special',
  'askd',
  'lunch',
  'lunch',
  'invited',
  'apartment',
  'went'],
 ['aight', 'yo', 'dat', 'straight', 'dogg'],
 ['please',
  'give',
  'connection',
  'today',
  'lt',
  'decimal',
  'gt',
  'refund',
  'bill'],
 ['shoot', 'big', 'load', 'get', 'ready'],
 ['bruv', 'hope', 'great', 'break', 'rewarding', 'semester'],
 ['home', 'always', 'chat'],
 ['good', 'study', 'well'],
 ['yup', 'noe', 'leh'],
 ['sound', 'great', 'home'],
 ['finally', 'match', 'heading', 'towards', 'draw', 'prediction'],
 ['tired', 'slept', 'well', 'past', 'night'],
 ['easy', 'ah', 'sen', 'got', 'selected', 'mean', 'good'],
 ['take', 'exam', 'march'],
 ['yeah',
  'think',
  'use',
  'gt',
  'atm',
  'register',
  'sure',
  'anyway',
  'help',
  'let',
  'know',
  'sure',
  'ready'],
 ['ok', 'prob', 'take', 'ur', 'time'],
 ['called',
  'ubandu',
  'run',
  'without',
  'installing',
  'hard',
  'disk',
  'use',
  'copy',

In [54]:
# check if the any word is empy space or not 
for sent in len(words):
    for word in len(sent):
        if word == ' ':
            print(word)

TypeError: 'int' object is not iterable

In [18]:
import gensim

In [19]:
# now train the word2vec from scratch
model = gensim.models.Word2Vec(words)

In [20]:
# to get all the vocabulary
model.wv.index_to_key

['call',
 'get',
 'ur',
 'gt',
 'lt',
 'go',
 'day',
 'ok',
 'free',
 'know',
 'come',
 'like',
 'good',
 'time',
 'got',
 'love',
 'text',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'going',
 'stop',
 'home',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'think',
 'tell',
 'week',
 'phone',
 'hi',
 'new',
 'later',
 'please',
 'pls',
 'co',
 'msg',
 'min',
 'dear',
 'night',
 'make',
 'message',
 'well',
 'say',
 'thing',
 'much',
 'hope',
 'oh',
 'claim',
 'great',
 'hey',
 'number',
 'give',
 'happy',
 'work',
 'friend',
 'wat',
 'way',
 'yes',
 'www',
 'let',
 'prize',
 'right',
 'tomorrow',
 'already',
 'tone',
 'said',
 'ask',
 'win',
 'amp',
 'cash',
 'life',
 'im',
 'yeah',
 'really',
 'babe',
 'meet',
 'find',
 'miss',
 'morning',
 'last',
 'service',
 'year',
 'uk',
 'thanks',
 'care',
 'would',
 'anything',
 'com',
 'also',
 'nokia',
 'lol',
 'every',
 'feel',
 'keep',
 'pick',
 'sure',
 'sent',
 'contact',
 'urgent',
 'something',
 'gud',
 'buy',
 'cant',
 'wait',
 'box',
 'place',
 'first',
 'even',
 'guy',
 'someone',
 'help',
 'went',
 'wish',
 'nice',
 'next',
 'tonight',
 'show',
 'soon',
 'word',
 'around',
 'money',
 'could',
 'customer',
 'many',
 'sleep',
 'chat',
 'late',
 'per',
 'ya',
 'sm',
 'always',
 'gonna',
 'wan',
 'leave',
 'name',
 'lot',
 'pm',
 'end',
 'dun',
 'told',
 'st',
 'person',
 'waiting',
 'special',
 'hello',
 'girl',
 'try',
 'fine',
 'month',
 'hour',
 'may',
 'minute',
 'coming',
 'heart',
 'haha',
 'people',
 'best',
 'th',
 'thk',
 'yet',
 'guaranteed',
 'smile',
 'done',
 'getting',
 'god',
 'ppm',
 'thought',
 'use',
 'offer',
 'start',
 'holiday',
 'class',
 'stuff',
 'talk',
 'line',
 'mean',
 'bit',
 'man',
 'live',
 'car',
 'lunch',
 'cost',
 'draw',
 'job',
 'finish',
 'problem',
 'never',
 'plan',
 'ill',
 'house',
 'hr',
 'better',
 'cool',
 'thats',
 'meeting',
 'trying',
 'yup',
 'mind',
 'ready',
 'dat',
 'account',
 'long',
 'pobox',
 'rate',
 'game',
 'weekend',
 'chance',
 'enjoy',
 'wk',
 'real',
 'half',
 'latest',
 'world',
 'sir',
 'bt',
 'guess',
 'po',
 'yo',
 'check',
 'play',
 'room',
 'pic',
 'voucher',
 'boy',
 'luv',
 'nothing',
 'wanna',
 'awarded',
 'sweet',
 'look',
 'eat',
 'camera',
 'receive',
 'lar',
 'shit',
 'big',
 'liao',
 'another',
 'landline',
 'birthday',
 'ah',
 'dinner',
 'xxx',
 'quite',
 'ever',
 'kiss',
 'might',
 'video',
 'jus',
 'age',
 'land',
 'watch',
 'watching',
 'wont',
 'question',
 'probably',
 'orange',
 'two',
 'baby',
 'thanx',
 'called',
 'tv',
 'dream',
 'worry',
 'aight',
 'bed',
 'pa',
 'hear',
 'nd',
 'speak',
 'fun',
 'early',
 'point',
 'princess',
 'bad',
 'den',
 'actually',
 'sat',
 'shall',
 'nite',
 'forgot',
 'part',
 'maybe',
 'ringtone',
 'left',
 'bus',
 'pay',
 'remember',
 'network',
 'apply',
 'office',
 'dunno',
 'made',
 'shopping',
 'reach',
 'easy',
 'hurt',
 'code',
 'dad',
 'wife',
 'fuck',
 'put',
 'true',
 'didnt',
 'everything',
 'face',
 'leh',
 'evening',
 'little',
 'award',
 'anyway',
 'xx',
 'dis',
 'mate',
 'town',
 'gift',
 'sound',
 'working',
 'mail',
 'yr',
 'school',
 'movie',
 'afternoon',
 'looking',
 'thank',
 'enough',
 'selected',
 'detail',
 'asked',
 'collect',
 'tmr',
 'missing',
 'without',
 'pound',
 'entry',
 'important',
 'hav',
 'xmas',
 'sexy',
 'join',
 'must',
 'price',
 'okay',
 'came',
 'pain',
 'since',
 'wanted',
 'valid',
 'though',
 'wif',
 'collection',
 'bring',
 'wot',
 'book',
 'wake',
 'able',
 'til',
 'answer',
 'abt',
 'mob',
 'run',
 'missed',
 'lesson',
 'update',
 'plus',
 'away',
 'de',
 'change',
 'plz',
 'charge',
 'decimal',
 'stay',
 'juz',
 'test',
 'wen',
 'date',
 'colour',
 'attempt',
 'bored',
 'dude',
 'weekly',
 'music',
 'shop',
 'else',
 'havent',
 'hair',
 'double',
 'yesterday',
 'saw',
 'till',
 'alright',
 'lei',
 'goin',
 'online',
 'drink',
 'friendship',
 'optout',
 'oso',
 'id',
 'coz',
 'haf',
 'top',
 'food',
 'making',
 'trip',
 'credit',
 'net',
 'family',
 'sch',
 'either',
 'feeling',
 'club',
 'hot',
 'gr',
 'smoke',
 'player',
 'address',
 'driving',
 'delivery',
 'tried',
 'ard',
 'national',
 'sad',
 'together',
 'lose',
 'sae',
 'beautiful',
 'tot',
 'head',
 'post',
 'calling',
 'full',
 'ring',
 'wid',
 'walk',
 'story',
 'si',
 'believe',
 'order',
 'nt',
 'busy',
 'bonus',
 'second',
 'mom',
 'http',
 'brother',
 'await',
 'drive',
 'saying',
 'mum',
 'eve',
 'poly',
 'huh',
 'chikku',
 'row',
 'happen',
 'noe',
 'sleeping',
 'hand',
 'leaving',
 'old',
 'smiling',
 'close',
 'info',
 'set',
 'drop',
 'rite',
 'email',
 'pub',
 'simple',
 'thinking',
 'suite',
 'mths',
 'okie',
 'wil',
 'awesome',
 'parent',
 'match',
 'private',
 'cause',
 'started',
 'finished',
 'took',
 'congrats',
 'tomo',
 'aft',
 'news',
 'hl',
 'auction',
 'anyone',
 'neva',
 'mine',
 'gd',
 'reason',
 'valentine',
 'sister',
 'card',
 'unsubscribe',
 'angry',
 'company',
 'tc',
 'break',
 'touch',
 'content',
 'everyone',
 'taking',
 'statement',
 'forget',
 'tho',
 'caller',
 'final',
 'available',
 'alone',
 'loving',
 'gal',
 'knw',
 'sun',
 'whatever',
 'opt',
 'dating',
 'choose',
 'found',
 'worth',
 'carlos',
 'bank',
 'fancy',
 'whats',
 'open',
 'type',
 'expires',
 'search',
 'ticket',
 'lucky',
 'treat',
 'hows',
 'party',
 'fast',
 'sub',
 'visit',
 'nyt',
 'kind',
 'welcome',
 'bout',
 'mobileupd',
 'far',
 'anytime',
 'congratulation',
 'secret',
 'gbp',
 'exam',
 'college',
 'boytoy',
 'frnd',
 'hard',
 'ltd',
 'ni',
 'quiz',
 'identifier',
 'uncle',
 'friday',
 'happened',
 'hit',
 'gone',
 'prob',
 'song',
 'decided',
 'saturday',
 'smth',
 'ha',
 'wonderful',
 'winner',
 'chennai',
 'least',
 'wrong',
 'lovely',
 'wonder',
 'drug',
 'sea',
 'pretty',
 'fri',
 'outside',
 'nope',
 'term',
 'fucking',
 'project',
 'light',
 'read',
 'hold',
 'tel',
 'oredi',
 'goodmorning',
 'darlin',
 'mrng',
 'finally',
 'wit',
 'mu',
 'operator',
 'used',
 'camcorder',
 'crazy',
 'support',
 'earlier',
 'snow',
 'listen',
 'savamob',
 'frm',
 'cum',
 'ten',
 'jay',
 'fone',
 'blue',
 'unlimited',
 'cd',
 'fr',
 'meant',
 'case',
 'course',
 'log',
 'hmm',
 'frnds',
 'whole',
 'telling',
 'seeing',
 'hungry',
 'wq',
 'sunday',
 'freemsg',
 'wkly',
 'father',
 'gas',
 'john',
 'enter',
 'luck',
 'film',
 'na',
 'gn',
 'knew',
 'understand',
 'store',
 'mayb',
 'sell',
 'sex',
 'paper',
 'area',
 'happiness',
 'yar',
 'un',
 'within',
 'park',
 'sk',
 'india',
 'as',
 'rock',
 'couple',
 'talking',
 'motorola',
 'moment',
 'currently',
 'ago',
 'txts',
 'reading',
 'christmas',
 'lost',
 'bslvyl',
 'die',
 'stupid',
 'single',
 'dnt',
 'side',
 'march',
 'balance',
 'mr',
 'hmmm',
 'joy',
 'tired',
 'invited',
 'felt',
 'mah',
 'computer',
 'load',
 'download',
 'hee',
 'cut',
 'move',
 'etc',
 'pas',
 'almost',
 'child',
 'eh',
 'valued',
 'press',
 'difficult',
 'grin',
 'surprise',
 'information',
 'heard',
 'photo',
 'sort',
 'extra',
 'ugh',
 'picking',
 'eye',
 'an',
 'xy',
 'darren',
 'kid',
 'gym',
 'max',
 'redeemed',
 'lady',
 'ipod',
 'doin',
 'supposed',
 'rental',
 'seen',
 'met',
 'ish',
 'figure',
 'via',
 'return',
 'ge',
 'swing',
 'laptop',
 'reveal',
 'bcoz',
 'semester',
 'bill',
 'direct',
 'sending',
 'askd',
 'shower',
 'gotta',
 'complimentary',
 'correct',
 'red',
 'ac',
 'wow',
 'hospital',
 'confirm',
 'charged',
 'promise',
 'comp',
 'police',
 'slowly',
 'loved',
 'fact',
 'fantasy',
 'nobody',
 'truth',
 'asap',
 'whenever',
 'idea',
 'laugh',
 'noon',
 'train',
 'door',
 'clean',
 'blood',
 'member',
 'rent',
 'monday',
 'remove',
 'asking',
 'yep',
 'slow',
 'discount',
 'hg',
 'ex',
 'weed',
 'small',
 'pete',
 'rest',
 'somebody',
 'hmv',
 'leaf',
 'wana',
 'lover',
 'road',
 'study',
 'kate',
 'orchard',
 'bath',
 'muz',
 'safe',
 'wine',
 'lovable',
 'txting',
 'dogging',
 'entered',
 'page',
 'loan',
 'save',
 'rply',
 'checking',
 'joke',
 'crave',
 'abiola',
 'cheer',
 'comin',
 'eg',
 'link',
 'wap',
 'reward',
 'request',
 'usf',
 'std',
 'empty',
 'med',
 'hw',
 'cover',
 'write',
 'bb',
 'ringtones',
 'energy',
 'doctor',
 'convey',
 'rd',
 'sale',
 'cr',
 'ntt',
 'otherwise',
 'poor',
 'gettin',
 'bag',
 'getzed',
 'summer',
 'wishing',
 'glad',
 'fantastic',
 'gap',
 'king',
 'ho',
 'indian',
 'em',
 'cheap',
 'warm',
 'across',
 'hoping',
 'less',
 'opinion',
 'near',
 'water',
 'different',
 'booked',
 'wc',
 'ldn',
 'voice',
 'mm',
 'mistake',
 'woke',
 'rakhesh',
 'custcare',
 'immediately',
 'merry',
 'normal',
 'somewhere',
 'tonite',
 'usual',
 'deep',
 'admirer',
 'kick',
 'street',
 'teach',
 'deal',
 'bathe',
 'spend',
 'pray',
 'sony',
 'del',
 'men',
 'gave',
 'representative',
 'il',
 'short',
 'forever',
 'situation',
 'reached',
 'oops',
 'catch',
 'turn',
 'worried',
 'england',
 'copy',
 'callertune',
 'nah',
 'cup',
 'la',
 'tear',
 'sofa',
 'colleague',
 'flag',
 'sitting',
 'thinkin',
 'excuse',
 'excellent',
 'moral',
 'reaching',
 'tht',
 'others',
 'wondering',
 'mode',
 'mon',
 'digital',
 'hiya',
 'mo',
 'iam',
 'gay',
 'user',
 'tampa',
 'fall',
 'charity',
 'comuk',
 'bid',
 'norm',
 'possible',
 'add',
 'seems',
 'bold',
 'starting',
 'pc',
 'forwarded',
 'hotel',
 'self',
 'silent',
 'meh',
 'style',
 'result',
 'kinda',
 'logo',
 'none',
 'al',
 'brings',
 'reference',
 'bluetooth',
 'urself',
 'round',
 'rcvd',
 'access',
 'cake',
 'accept',
 'sport',
 'rose',
 'unless',
 'disturb',
 'ldew',
 'goodnight',
 'ive',
 'mrt',
 'dead',
 'using',
 'trust',
 'studying',
 'especially',
 'doesnt',
 'staying',
 'completely',
 'lect',
 'lazy',
 'sunshine',
 'buying',
 'ending',
 'flight',
 'specially',
 'bos',
 'coffee',
 'password',
 'rain',
 'stand',
 'ip',
 'bx',
 'ice',
 'decide',
 'sick',
 'seriously',
 'issue',
 'mood',
 'pix',
 'er',
 'wednesday',
 'list',
 'inside',
 'south',
 'fill',
 'frens',
 'vl',
 'dog',
 'picked',
 'honey',
 'complete',
 ...]

In [21]:
model.epochs

5

In [22]:
model.wv.similar_by_word('happy')

[('year', 0.9993683099746704),
 ('day', 0.9993640780448914),
 ('amp', 0.999302864074707),
 ('wish', 0.999294638633728),
 ('dear', 0.9992604851722717),
 ('thought', 0.9992237687110901),
 ('heart', 0.999222457408905),
 ('said', 0.9992177486419678),
 ('love', 0.9992141723632812),
 ('keep', 0.9991954565048218)]

In [23]:
!pip install tqdm

Requirement already satisfied: tqdm in d:\anaconda\lib\site-packages (4.67.1)
Requirement already satisfied: colorama in d:\anaconda\lib\site-packages (from tqdm) (0.4.6)

In [24]:
from tqdm import tqdm
# used for understadingthe progress for the long loop runnign

In [25]:
# to run the avg wrod2vec we need to first rnsure that the normal word2vec model is ready and for each word we find the 
# model.wv[word] means the vector and with the help of np.means cal the mean value in the horizontal direction

In [26]:
# the normal vector for any word looks like 
model.wv['king']
model.wv['king'].shape

(100,)

In [27]:
model.wv['king']

array([-0.03787312,  0.07517619, -0.00240437,  0.02539666,  0.0089729 ,
       -0.14226782,  0.01986707,  0.14590046, -0.04414564, -0.04311326,
       -0.04784903, -0.1043067 , -0.03994939,  0.03632161,  0.01562185,
       -0.05031075, -0.00269807, -0.11017288, -0.00199031, -0.16117814,
        0.03726039,  0.07091758,  0.04557773, -0.04975016, -0.03670277,
       -0.01838002, -0.08311333, -0.09017307, -0.07120327,  0.02137408,
        0.10057627,  0.01535146,  0.02657479, -0.02996566, -0.02831287,
        0.10483888, -0.00100292, -0.08138499, -0.06615203, -0.19066423,
        0.0038228 , -0.06272648, -0.01504836,  0.01431831,  0.09318336,
       -0.03488824, -0.03866839, -0.02835307,  0.05796404,  0.02018412,
        0.04862423, -0.06647884, -0.02287669, -0.00031997, -0.05637871,
        0.03709175,  0.0539638 , -0.00509747, -0.08048759, -0.00096265,
        0.0380873 ,  0.01195419, -0.02865795, -0.0126327 , -0.12841293,
        0.04148085,  0.04937915,  0.06158382, -0.11344336,  0.09941388,
       -0.05005727,  0.00623299,  0.10314516, -0.01577503,  0.10667471,
        0.03550281, -0.00757069, -0.01144434, -0.06870938,  0.01305921,
       -0.01645847,  0.01389918, -0.0546516 ,  0.11923683, -0.02838859,
        0.01997929,  0.01136913,  0.10176847,  0.11915901,  0.037803  ,
        0.08291684,  0.06361828, -0.01337147,  0.04535709,  0.12750858,
        0.10222266,  0.02744088, -0.08417906,  0.05853577, -0.00899086],
      dtype=float32)

In [37]:
import numpy as np

def avg_word2vec(doc):
    # Collect vectors for words present in the model vocabulary
    # if word present in the model vocabulary then find its vector 
    vector_list =  [ model.wv[word] for word in doc if word in model.wv]

    # row wise mean
    return np.mean(vector_list,axis = 0)

In [ ]:
# now we are converting each word in the sentece mean
# after creatiing the word2vec model each word vecote is in the shape of the 100 rows and 1 col 
# so we can take the each word from sentence and transform into the one vector of dimension 100 in shape 100 rows and 1 col for one sent
# after that owr data is ready for model training

# also check the no of data points for x train and y train should be equal f
# if not equal make it equal by removng from the train data

In [46]:
# now apply the fucntion to the sentence 
X = []
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

100%|████████████████████████████████████████████████████████████████████████████| 5572/5572 [00:00<00:00, 8950.82it/s]

In [51]:
X[0].shape

(100,)

In [48]:
len(X)

5572

In [31]:
len(words)

5572

In [32]:
# now X contains the vecotorize form of each sentence in each index

In [55]:
X[0]

array([-1.44944370e-01,  2.32737556e-01, -1.19729480e-03,  8.37667510e-02,
        1.67186037e-02, -4.17657256e-01,  8.46612677e-02,  4.72721785e-01,
       -1.47422090e-01, -1.39959589e-01, -1.61265135e-01, -3.22935551e-01,
       -1.02554820e-01,  1.35158285e-01,  5.09973913e-02, -1.42685026e-01,
        5.32978447e-03, -3.59746456e-01, -1.98549666e-02, -4.65285033e-01,
        9.00381953e-02,  1.90649554e-01,  1.10943429e-01, -1.56261295e-01,
       -1.15186982e-01, -6.52460605e-02, -2.60598063e-01, -2.65862197e-01,
       -2.02773854e-01,  7.65334591e-02,  3.31387728e-01,  3.73007394e-02,
        1.02957934e-01, -8.50269869e-02, -7.33060613e-02,  3.28247845e-01,
       -3.54881748e-04, -2.29547277e-01, -1.99535653e-01, -5.56617320e-01,
        4.05075774e-02, -1.70186788e-01, -2.11586971e-02,  1.72918811e-02,
        2.63853937e-01, -1.01599552e-01, -1.44771844e-01, -6.18225075e-02,
        1.55826062e-01,  7.38926530e-02,  1.53613120e-01, -1.82758108e-01,
       -4.69740964e-02,  5.60730696e-03, -1.94233090e-01,  9.06116143e-02,
        1.45256221e-01, -3.67648751e-02, -2.75741756e-01,  2.09042653e-02,
        9.11495909e-02,  3.81811000e-02, -8.37687925e-02, -3.19751091e-02,
       -3.88489425e-01,  1.24729298e-01,  1.51209697e-01,  2.01982111e-01,
       -3.68635476e-01,  3.16595912e-01, -1.38430834e-01,  3.19297947e-02,
        2.88397878e-01, -5.74210435e-02,  3.16702604e-01,  1.31546363e-01,
       -4.09840839e-03, -4.83826175e-02, -1.97410107e-01,  6.26151860e-02,
       -2.26167422e-02,  2.57477574e-02, -1.54311776e-01,  3.76714587e-01,
       -8.06657895e-02,  7.11111501e-02,  1.53885195e-02,  3.07059914e-01,
        3.62962931e-01,  1.03133708e-01,  2.63110340e-01,  1.78735822e-01,
       -3.46446559e-02,  1.40020952e-01,  4.15706664e-01,  2.89275736e-01,
        7.76866823e-02, -2.80151069e-01,  1.73821554e-01, -4.63555604e-02],
      dtype=float32)

In [70]:
# independent features
type(X)

list

In [71]:
len(X)

5572

In [72]:

import numpy as np
my_array = np.array(X)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (5572,) + inhomogeneous part.

In [75]:
# make the dependent freature y
y = pd.get_dummies(message['label'],dtype=int)

In [76]:
y

      ham  spam
0       1     0
1       1     0
2       0     1
3       1     0
4       1     0
...   ...   ...
5567    0     1
5568    1     0
5569    1     0
5570    1     0
5571    1     0

[5572 rows x 2 columns]

In [77]:
y=y.iloc[:,0]

In [78]:
y

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: ham, Length: 5572, dtype: int64

In [80]:
len(y)

5572

In [91]:
# Find rows that do not have a shape of (100,)
for index, vector in enumerate(X):
    if vector.shape != 100:
        print(index,vector[0].shape)

0 ()
1 ()
2 ()
3 ()
4 ()
5 ()
6 ()
7 ()
8 ()
9 ()
10 ()
11 ()
12 ()
13 ()
14 ()
15 ()
16 ()
17 ()
18 ()
19 ()
20 ()
21 ()
22 ()
23 ()
24 ()
25 ()
26 ()
27 ()
28 ()
29 ()
30 ()
31 ()
32 ()
33 ()
34 ()
35 ()
36 ()
37 ()
38 ()
39 ()
40 ()
41 ()
42 ()
43 ()
44 ()
45 ()
46 ()
47 ()
48 ()
49 ()
50 ()
51 ()
52 ()
53 ()
54 ()
55 ()
56 ()
57 ()
58 ()
59 ()
60 ()
61 ()
62 ()
63 ()
64 ()
65 ()
66 ()
67 ()
68 ()
69 ()
70 ()
71 ()
72 ()

IndexError: invalid index to scalar variable.

In [ ]:
# it means to convert the X into the array i need to remove these x words vectors form the whle x

In [92]:
import numpy as np

# 1. Create clean lists by checking the shape of each vector
cleaned_X = []
cleaned_y = []

for vec, label in zip(X, y):
    if np.shape(vec) == (100,):
        cleaned_X.append(vec)
        cleaned_y.append(label)

# 2. Convert to final NumPy arrays
X_final = np.array(cleaned_X)
y_final = np.array(cleaned_y)

print("New X shape:", X_final.shape)
print("New y shape:", y_final.shape)



# note 
# when the each vector  is appended isndie the cleaned_x its the vertical wise for eah sent vector when i do he kto array 2d conversion it make the 
# each into he all 100 dimensions into the col and data points as rows

New X shape: (5496, 100)
New y shape: (5496,)

In [94]:
X_final[0].shape

(100,)

In [95]:
y_final.shape

(5496,)

In [96]:
# now owr data is ready to do the trainig 
# now apply the model like random forst classifier stuff